spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lessons?characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: terry
  jpa:
    database: MySQL
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update